# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0c335a1e6415b91da45c17df8fc00b1ccd5b6cd9329cc0f25a93a2a98217b4bd12547dba9ecbba3f91f4f23341dd5954b6726ccd56cbd2ca603b86042ed0bb3b

test:
  secret_key_base: c38b77b8374e9abbc84d5a2ace036bdd1bbccb284e501a6910e3b2ffd9a0bdadb9a3be2e3e60ae2666d348c33972615588c3140cb30dc00cdaece4cd732e5cd1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
